### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by ajithkumarpalani1** [EliCDavis/ng-conditionally-validate#3]
Hi, 

I am working on version upgrade of my project. This package is not supporting Angular 13, I need alternative for this. Kindly help me on this. Thanks in advance

**Comment by EliCDavis** [comment]
Hi, what issues is the package throwing when you upgrade to Angular 13?

**Comment by ajithkumarpalani1** [comment]
@EliCDavis Getting below error in browser console while running the app

Error: Uncaught (in promise): TypeError: conditionLatest$.map is not a function
TypeError: conditionLatest$.map is not a function
    at Object.is (conditionally-validate.service.js:69:1)
    at new IntellectAuthenticationSecurityQuestionsPageComponent (intellect-authentication-security-questions-page.component.ts:106:8)
    at NodeInjectorFactory.IntellectAuthenticationSecurityQuestionsPageComponent_Factory [as factory] (ɵfac.js? [sm]:1:1)
    at getNodeInjectable (core.mjs:3565:1)
    at instantiateRootComponent (core.mjs:10181:1)
    at createRootComponent (core.mjs:12285:1)
    at ComponentFactory.create (core.mjs:21638:1)
    at ViewContainerRef.createComponent (core.mjs:22902:1)
    at RouterOutlet.activateWith (router.mjs:2521:40)
    at ActivateRoutes.activateRoutes (router.mjs:2161:40)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25579:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1648:1)



And intellect-authentication-security-questions-page.component.ts:106:8 is 

104:   this.selfQuestion1$ = this.conditionalValidator
105      .validate(<FormGroup>this.securityQuestionsFormGroup, 'question1Type.selfQuestion1')
104      .using(Validators.required)
105:      .when('question1')
106:      **.is('Write my own question');**

**Comment by EliCDavis** [comment]
Ah simple enough. Yeah, this is on a super old version of RXJS. I'll see if I can get to it this weekend.

**Comment by ajithkumarpalani1** [comment]
Yeah, I am using Rxjs version of 6.6.3 in my Angular 13 application, Requesting you to get this issue resolved asap. Thanks
